//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWT.United.UI.Controls.UserControls.MasterPageControls {
    
    
    public partial class _SampleControl {
    }
}
